library(readr)
bank.additional <- read.csv("E:/kamagyana/Computing/DARET/Assignments/bank-additional.csv", sep=";", stringsAsFactors=FALSE)
str(bank.additional)
sum(is.na(bank.additional))
library(VIM)
missdataplot <- aggr(bank.additional, col=c('navyblue','red'), numbers=TRUE, sortVars=TRUE, labels=names(data), cex.axis=.7, gap=3, ylab=c("Histogram of missing data","Pattern"))
JobDefault <- table(bank$job, bank$default)
addmargins(JobDefault)
chisq.test(JobDefault)
class(JobDefault)
JobDefault <- JobDefault[-c(6,7,9,11,12),]
JobDefault
chisq.test(JobDefault)
library(sqldf)
library(dplyr)
hyesno <- bank.additional %>% filter (housing == "yes"|housing == "no") %>% select(housing,duration)
head(hyesno)
summary(hyesno %>% filter(housing == "yes") %>% .$duration)
summary(hyesno %>% filter(housing == "no") %>% .$duration)
summary(hyesno$duration)
library(ggplot2)
ggplot(hyesno,aes(housing, duration)) + geom_boxplot()
p1 <- ggplot(hyesno, aes(duration)) +
geom_histogram(fill = "white", color = "grey30") +
facet_wrap(~ housing)
p1
t.test(duration~housing, data=hyesno)
sum(is.na(hyesno$duration))
wilcox.test(duration~housing, data=hyesno)
colnames(bank.additional)
sum(is.na(bank.additional$cons.price.idx))
summary(bank.additional$cons.price.idx)
summary(bank.additional$cons.conf.idx)
library(Hmisc)
rcorr(bank.additional$cons.conf.idx, bank.additional$cons.price.idx)
plot(bank.additional$cons.conf.idx,bank.additional$cons.price.idx)
jobemp <- bank.additional %>% select(job,emp.var.rate)
jobemp$job <- gsub('blue-collar','bluecollar',jobemp$job)
jobemp$job <- gsub('self-employed','selfemployed',jobemp$job)
jobemp$job <- as.factor(jobemp$job)
str(jobemp)
ggplot(jobemp,aes(job,emp.var.rate)) + geom_boxplot() + scale_x_discrete(labels =abbreviate)
result <- aov(emp.var.rate~job,data=jobemp)
summary(result)
library(stats)
TukeyHSD(result)
jobemp2 <- jobemp %>% filter(job != "student" & job != "selfemployed" & job != "retired" & job != "unemployed") %>% select(job,emp.var.rate)
table(jobemp2$job)
result <- aov(emp.var.rate~job,data=jobemp2);
summary(result)
TukeyHSD(result)
empedu <- bank.additional %>% select(education,emp.var.rate)
head(empedu)
ggplot(empedu,aes(education,emp.var.rate)) + geom_boxplot() + scale_x_discrete(labels =abbreviate)
result <- aov(emp.var.rate~education,data=empedu);
summary(result);
TukeyHSD(result)
jobconf <- bank.additional %>% select(job,cons.conf.idx);
head(jobconf)
ggplot(jobconf,aes(job,cons.conf.idx)) + geom_boxplot() + scale_x_discrete(labels =abbreviate)
result <- aov(cons.conf.idx~job,data=jobconf);
summary(result);
TukeyHSD(result)
group_by(jobconf,job) %>% summarise(conf = mean(cons.conf.idx))